
version: "3"

services:
  mongodb1:
    image: mongo
    container_name: mongodb1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password1!
    command: mongod --replSet rs0 --keyFile /key/mongodb.key --bind_ip_all
    ports:
      - 4001:27017
    volumes:
      - ./key:/key
      - ./mongodb1:/data/db
    networks:
      - mongoCluster
  mongodb2:
    image: mongo
    container_name: mongodb2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password1!
    command: mongod --replSet rs0 --keyFile /key/mongodb.key --bind_ip_all
    ports:
      - 4002:27018
    volumes:
      - ./key:/key
      - ./mongodb2:/data/db
    networks:
      - mongoCluster



networks:
  mongoCluster:
    external: true