version: "3"

services:
  mongodb1:
    image: mongo:latest
    hostname: mongodb1
    container_name: mongodb1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1!
    volumes:
      - ./mongodb1/mongod.conf:/etc/mongod.conf
      - ./key/mongodb.key:/etc/mongodb.key
      - ./data/mongodb1:/data/db
    command: mongod --replSet rs0 --port 27018 --keyFile /etc/mongodb.key --bind_ip_all
    ports:
      - 27018:27018
    networks:
      - hsjNetwork
  mongodb2:
    image: mongo:latest
    hostname: mongodb2
    container_name: mongodb2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1!
    volumes:
      - ./mongodb2/mongod.conf:/etc/mongod.conf
      - ./key/mongodb.key:/etc/mongodb.key
      - ./data/mongodb2:/data/db
    command: mongod --replSet rs0 --port 27019 --keyFile /etc/mongodb.key --bind_ip_all
    ports:
      - 27019:27019
    networks:
      - hsjNetwork
    depends_on:
      - mongodb1
  mongodb3:
    image: mongo:latest
    hostname: mongodb3
    container_name: mongodb3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1!
    volumes:
      - ./mongodb3/mongod.conf:/etc/mongod.conf
      - ./key/mongodb.key:/etc/mongodb.key
      - ./data/mongodb3:/data/db
    command: mongod --replSet rs0 --port 27020 --keyFile /etc/mongodb.key --bind_ip_all
    ports:
      - 27020:27020
    networks:
      - hsjNetwork
    depends_on:
      - mongodb1


  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - 6379:6379
  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - 6380:6379


  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: hsjmysql15!
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d


networks:
  hsjNetwork:
    external: true