spring:
  profiles:
    active: local
    include:
      - db
#      - mongo
#      - mysql
#      - redis
      - security


---
spring:
  config:
    activate:
      on-profile: local



#logging:
#  level:
#    org:
#      springframework:
#        transaction.interceptor: TRACE