spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: create # 실제 서버에서 사용시 모든 데이터가 다 날아가므로 주의
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true